TEAM-ACO/aco-back

- compose.yml
- src/main/java/dev/aco/back/Controller/MemberController.java
- src/main/java/dev/aco/back/DTO/MemberDTO.java
- src/main/java/dev/aco/back/Entity/User/Member.java
- src/main/java/dev/aco/back/Entity/User/emailAuth.java
- src/main/java/dev/aco/back/Repository/MailRepository.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/VO/signUp.java
- src/main/java/dev/aco/back/service/MailService/AcoMailSender.java
- src/main/java/dev/aco/back/service/MailService/MailService.java
- src/main/java/dev/aco/back/service/MailService/MailServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberService.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
MemberController : signUp 작성
DTO : MemberDTO 작성
MailRepository, MailSender 작성
MemberService : signUp, email, mobile 중복체크 기능 작성
> [김형준] 회원가입

- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/Security/DTO/SecurityMemberDTO.java
- src/main/java/dev/aco/back/Security/Filter/CustomLoginFilter.java
- src/main/java/dev/aco/back/Security/Handler/CustomSuccessHandler.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
- src/main/java/dev/aco/back/Security/Service/CustomLoginService.java
- src/main/java/dev/aco/back/Security/Service/CustomOAuth2Service.java
- src/main/java/dev/aco/back/Security/Vender/OAuthAttributes.java
- src/main/java/dev/aco/back/Utils/JWT/JWTManager.java
- src/main/java/dev/aco/back/Utils/Redis/RedisConfig.java
- src/main/java/dev/aco/back/Utils/Redis/RedisManager.java
포크 잘못했나봅니다 .. 다음부터는 포크 다시해서 제대로 pr넣을게용 ..
site로그인, oauth2로그인 넣었구요
oauth2는 설정을 더 봐야하고
실제로 로그인 가능한지는 해봐야압니다 흑흑..
순차는
사이트/oauth2로그인 > 성공 > response header에 쿠키설정
> [Hyunseok] Add site/oauth2 login function

- pom.xml
- src/main/java/dev/aco/back/Controller/MemberController.java
- src/main/java/dev/aco/back/DTO/MemberDTO.java
- src/main/java/dev/aco/back/Entity/User/emailAuth.java
- src/main/java/dev/aco/back/Security/Service/CustomLoginService.java
- src/main/java/dev/aco/back/Security/Service/CustomOAuth2Service.java
- src/main/java/dev/aco/back/Utils/Image/ImageManager.java
- src/main/java/dev/aco/back/service/MailService/MailServiceImpl.java
- src/main/resources/META-INF/additional-spring-configuration-metadata.json
간단한 이미지 매니저 작성해놨어요
Utils - Image - ImageManager
Javamail > jakartamail로 3버전나와서 pom.xml 교체해놨어용
그리고 기타 entity랑 작성되어있는 다른 파일들 이름 꼬인 것도 몇개 해결해놨어용
> [Hyunseok] Add imageManager and fix minor issues

- pom.xml
- src/main/java/dev/aco/back/Controller/MemberController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ArticleImageDTO.java
- src/main/java/dev/aco/back/DTO/Article/RecommendDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/DTO/MemberDTO.java
- src/main/java/dev/aco/back/DTO/Report/ArticleReportDTO.java
- src/main/java/dev/aco/back/DTO/Report/MemberReportDTO.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
- src/main/java/dev/aco/back/DTO/Visitor/VisitorDTO.java
- src/main/java/dev/aco/back/Entity/User/emailAuth.java
- src/main/java/dev/aco/back/Repository/ArticleReportRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
- src/main/java/dev/aco/back/Repository/VisitorRepository.java
- src/main/java/dev/aco/back/Security/Service/CustomLoginService.java
- src/main/java/dev/aco/back/Security/Service/CustomOAuth2Service.java
- src/main/java/dev/aco/back/Utils/Image/ImageManager.java
- src/main/java/dev/aco/back/service/MailService/MailServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberService.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
- src/main/resources/META-INF/additional-spring-configuration-metadata.json
필요해보이는 DTO랑 레포지토리 생성해뒀습니다
추후 필요한 DTO랑 레포지토리는 생성해서 사용해주시면 괜찮구용
중간에 Entity이름 변경하시면 꼭 댓글이나 디스코드로 언급해주세요 !
> [Hyunseok] Initialize required basic dto and repositories

- pom.xml
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ArticleImageDTO.java
- src/main/java/dev/aco/back/DTO/Article/RecommendDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/DTO/Report/ArticleReportDTO.java
- src/main/java/dev/aco/back/DTO/Report/MemberReportDTO.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
- src/main/java/dev/aco/back/DTO/Visitor/VisitorDTO.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Repository/ArticleReportRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/MemberReportRepository.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
- src/main/java/dev/aco/back/Repository/VisitorRepository.java
- src/main/java/dev/aco/back/Security/Filter/CustomLoginFilter.java
- src/main/java/dev/aco/back/Security/Handler/CustomSuccessHandler.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
- src/main/java/dev/aco/back/Security/Service/CustomLoginService.java
- src/main/java/dev/aco/back/Utils/JWT/JWTManager.java
- src/main/java/dev/aco/back/VO/LoginVO.java
- src/main/java/dev/aco/back/service/MailService/AcoMailSender.java
- src/main/java/dev/aco/back/service/MemberService/MemberService.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
로그인 필터 뭔가 날라가있어서 다시 실장했구영
여러 문제들 조금있어서 수정했고
post 신호로 사이트 로그인까지 테스트 끝냈습니다
> [Hyunseok] Implement login filter, fix minor issues

- pom.xml
- src/main/java/dev/aco/back/Controller/EmailController.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
http://localhost:15251/api/swagger-ui.html
위의 주소로 접근 가능합니다
> [Hyunseok] Implement openapi for apidoc

- src/main/java/dev/aco/back/BackApplication.java
- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/ImageController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
- src/main/java/dev/aco/back/Entity/Article/Reply.java
- src/main/java/dev/aco/back/Entity/User/Member.java
- src/main/java/dev/aco/back/Repository/ArticleImageRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/HashtagRepository.java
- src/main/java/dev/aco/back/Repository/Linker/HashArticleLInker.java
- src/main/java/dev/aco/back/Repository/RecommendRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
1. 페이징 미완성
2. N+1 미해결
- N+1은 다음 주에 해결할게용
- 페이징은 수요일까지 마무리해놓을게영
> [Hyunseok] Implement printing article list function without paging

- src/main/java/dev/aco/back/Security/Handler/CustomSuccessHandler.java
- src/main/java/dev/aco/back/Security/Service/CustomLoginService.java
쿠키에서 일단 급하게 JSON으로 response설정해놨어용
> [Hyunseok] Hotfix for login

- src/main/java/dev/aco/back/Controller/ReportController.java
- src/main/java/dev/aco/back/DTO/Report/ArticleReportDTO.java
- src/main/java/dev/aco/back/service/ReportService/ReportService.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
간단한 사용자/글 신고 기능
ArticleReportDTO, MemberReportDTO 기준으로 신호보내면 신고가 저장됩니다
주소는 /report/member or article로..
예시는 swagger참조해주세용
> [Hyunseok] Implement add report article/member function

- src/main/java/dev/aco/back/Controller/MemberSettingController.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/VO/ChangeUserImgVO.java
- src/main/java/dev/aco/back/VO/SignupVO.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberSettingService.java
- src/main/java/dev/aco/back/service/MemberService/MemberSettingServiceImpl.java
**[추가된 내용]**
MemberSettingService 와 MemberSettingController에 changeUserImg 기능을 추가했습니다만..
Projection 을 위해서 VO 클래스를 작성했습니다만..
**[사족]**
개인적인 사정으로 저번주는 전혀 작업을 하지 못했습니다 죄송합니다.
Member Entity에 String Type으로 저장되는 userimg 와 ImageManager의 MultipartRequest 의 File의 타입이 다른데 요걸 어떻게 작성하는지 잘 모르겠습니다.. 나름대로 검색해서 찾아봤는데 해결하지 못했습니다. 죄송합니다.
> [Hyeongjun] Add Change Member Profile img 

- src/main/java/dev/aco/back/Security/Filter/CustomLoginFilter.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
- src/main/java/dev/aco/back/Security/Service/CustomOAuth2Service.java
- src/main/java/dev/aco/back/Security/Vender/OAuthAttributes.java
구글/카카오 oauth2 로그인 테스팅까진 다끝내놨어용
일반 로그인이랑 똑같이 처리해주셔용
initoauth페이지로 넘어가는것만 담주에시작합시당
@k1k2brz 프론트에 로그인 주소는 /api/login에서 /api/member/login으로 바꿔주세용 ㅠㅠ ..
> [Huynseok] Implement oauth2 login(google/kakao)

- pom.xml
- src/main/java/dev/aco/back/DirectMessage/DTO/ChatMessage.java
- src/main/java/dev/aco/back/DirectMessage/DTO/RoomInfo.java
- src/main/java/dev/aco/back/DirectMessage/DirectMessageConfig.java
- src/main/java/dev/aco/back/Utils/Redis/RedisConfig.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
> [Hyunseok] Initialize direct message function

- compose.yml
- pom.xml
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Article/ArticleImage.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/Utils/Image/ImageManager.java
- src/main/java/dev/aco/back/VO/ChangePasswordVO.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberSettingServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
**[바뀐내용]**
ArticleDTO : articleImages 가 String ==> List<MultipartReqeust> 타입으로 변경
ArticleService 클래스의 write 매서드에 이미지 첨부 수정 forEach사용해 이미지 업로드후 airepo에 이미지들 저장
**[사족]**
readList 의 리턴값 ArticleDTO 가 변경되면서 readList가 빨간불이 엄청 들어왔는데, 뭘 건드려야 될지 모르겠어서 일단..  주석처리했습니다. 죄송합니다. 
코멘트 단 것처럼 airepo 에 save하는 과정에서 img(String 타입) 을 저장하기 위해서 임시로 String uploadedImgStr 변수 추가했습니다..  이렇게 하면 imageManger에 매서드 추가없이 가능하지 않을까 싶어서..
내일 일어나는대로 피드백 주신거 확인하고 고쳐보겠습니다.
> [Hyeongjun] Fix Article Write (Image)

- src/main/java/dev/aco/back/Controller/ReportController.java
- src/main/java/dev/aco/back/Repository/ArticleReportRepository.java
- src/main/java/dev/aco/back/service/ReportService/ReportService.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
> [Hyunseok] Fix article report logic

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/ReportController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Article/Hashtag.java
- src/main/java/dev/aco/back/Repository/ArticleReportRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyService.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyServiceImpl.java
- src/main/java/dev/aco/back/service/ReportService/ReportService.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
Entitygraph로 싹 불러왔구영 
reply도 같이넣으려하니 계속 페이징이 이상하게 되어서 .. 
그냥 따로 빼서 넣었습니다 (배보다 배꼽이 더커짐.. 흑흑)
댓글 작성.. 되는지 테스트는 안했는데 
작성 로직도 컨트롤러 포함해서 작성해놓았습니다
> [Hyunseok]Fix n+1 problem for get article list

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/ReportController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Article/Hashtag.java
- src/main/java/dev/aco/back/Repository/ArticleReportRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyService.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyServiceImpl.java
- src/main/java/dev/aco/back/service/MemberService/MemberService.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
- src/main/java/dev/aco/back/service/ReportService/ReportService.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
> [Hyunseok] Hotfix for signup

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
1. article에 toDTO 작성
2. 멤버번호로 리스트 뽑아내는 기능 구현(반환값은 readList랑 같음)
ㄴ api/article/list/멤버번호
3. RequestMapping > PostMapping
> [Hyunseok] Implement readlist function by member id

- pom.xml
- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Article/ArticleNoun.java
- src/main/java/dev/aco/back/Repository/ArticleNounRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
자연어 처리 라이브러리로 자연어 싹 뽑아낸뒤
게시글 등록할때 Noun테이블에 같이 다 넣어버립니다
검색할때, Noun테이블의 Noun값이 같은 내용들을 싹 뽑아옵니다 
1. ArticleNoun 엔티티 추가
2. 검색기능 추가
1차적으로 테스팅은 일단 해서 나오는거 확인하긴했는데 
프론트에서 fetch할 때 정상적으로 나오는가 함 더 확인해주세영
> [Hyunseok] Implement search function by given nouns

- pom.xml
- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Linker/ArticleHashtag.java
- src/main/java/dev/aco/back/Repository/ArticleNounRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/Linker/HashArticleLInker.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
검색에다 해시태그도 같이 검색 가능하게끔 만들어놨습니다
DB딱 3번만 긁습니다 이거 어케 잘 하면 그냥 한번에 싸악 불러올수있을듯한데 .. 
넘 지쳐서 .. 생각나면 다시 개조해볼게영 ..
> [Hyunseok] Implement tag search include on normal search

- pom.xml
- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Entity/Article/ArticleNoun.java
- src/main/java/dev/aco/back/Repository/ArticleNounRepository.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
메뉴 번호대로 리스트 뽑는 기능
메뉴 번호
ㄴ 0: Diary, 1: Tip, 2:Question
여타 다른 list뽑듯 pageVO 바디에 보내주시고 주소는
api/aritlce/menu/{메뉴번호}
> [Hyunseok] Implement readlist function by menu

- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
- src/main/java/dev/aco/back/Admin/Service/AdminService.java
- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/Repository/VisitorRepository.java
- src/main/java/dev/aco/back/VO/VisitorVO.java
급하게 만들어서 테스트..는 해봐야 알겠지만 일단 
메인페이지 - 방문자 분석정보(선택 주 토탈, 일별 방문자, 유입 링크, 방문된 게시글 정보), 각 카테고리별 5개씩 정보들
게시글, 멤버, 신고(게시글, 멤버) 리스트 출력, id별로 삭제 기능
테스트는 다음 주에 해볼게용
> [Hyunseok] Implement read/delete admin functions

- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
- src/main/java/dev/aco/back/Admin/Service/AdminService.java
- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/MemberRepository.java
- src/main/java/dev/aco/back/Repository/VisitorRepository.java
- src/main/java/dev/aco/back/Security/Handler/CustomSuccessHandler.java
- src/main/java/dev/aco/back/VO/VisitorVO.java
로그인 후 쿠키가 안들어가는 버그 수정
원래라면 나가는 쿠키도 암호화 해주는게 좋을듯한데 .. 
일단 이번 프로젝트는 여기까지만 합시당
> [Hyunseok] Fix cookie issue

- src/main/java/dev/aco/back/Controller/LikeController.java
- src/main/java/dev/aco/back/Entity/Article/Article.java
- src/main/java/dev/aco/back/Repository/ArticleNounRepository.java
- src/main/java/dev/aco/back/Repository/LikeRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleLikeService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleLikeServiceImpl.java
- src/main/java/dev/aco/back/service/MailService/MailServiceImpl.java
- src/test/java/dev/aco/back/BackApplicationTests.java
> [Hyunseok] Remove unnecessary lines

- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
어드민 리스트 get > post로 변경
paging객체 잘못생성된거 수정
> [Hyunseok] Fix some lines for admin logic

- compose.yml
- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/Security/Filter/CustomUserFilter.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyServiceImpl.java
나중에 사용자가 요구되는 기능 주소는 
Security > Filter > CustomUserFilter 에서 
주소 추가해줘야합니다
프론트에서는 추가된 주소에 대해 
자료를 요청할때 헤더에는 
atk = 엑세스토큰, htk = 리프래시토큰을 
기재해줘야합니다
기타 값 잘못들어가는 것도 몇개 바꿔놨습니다
> [Hyunseok] Implement filter for effect to user and fix some issue

- compose.yml
- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/ReplyDTO.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Security/Filter/CustomUserFilter.java
- src/main/java/dev/aco/back/Security/SecurityConfig.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyServiceImpl.java
liker 추가, 전체 목록에서 hashtag가 안묶였던 버그 수정
> [Hyunseok] Fix query for n+1 by liker added

- src/main/java/dev/aco/back/Admin/Controller/AdminController.java
memberrportid인줄알았는데 userReportId였네여 .. 수정해놨습니당
> [Hyunseok] Fix issue for memberreport

- src/main/java/dev/aco/back/Controller/LikeController.java
- src/main/java/dev/aco/back/Repository/LikeRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleLikeServiceImpl.java
Controller >> RequestBody import가 잘못되어있어서 수정했어용
Repository >> memberid, articleid로 찾기용 하나 만들어놨어용
Service >> ifPresentOrElse로 간략하게 짜놨어용
성공 > true
실패 > false
> [Hyunseok] Update article like function

- src/main/java/dev/aco/back/Entity/Article/Article.java
> [Hyunseok] Fix issue for delete article

- src/main/java/dev/aco/back/Entity/User/Member.java
- src/test/java/dev/aco/back/BackApplicationTests.java
> [Hyunseok] Fix delete function for memeber

- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
> [Hyunseok] Fix issue which memberid not loaded

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/ImageController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/etc/locationDTO.java
- src/main/java/dev/aco/back/Entity/etc/Location.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/HashtagRepository.java
- src/main/java/dev/aco/back/Repository/LocationRepository.java
- src/main/java/dev/aco/back/Utils/Image/ImageManager.java
- src/main/java/dev/aco/back/VO/ChangeUserImgVO.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
해시태그 오류 수정
이미지 업로드 이슈 수정
게시글 페이징 오류 수정 (fetch > inner)
> [Hyunseok] Fix article write function

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/ImageController.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Article/etc/locationDTO.java
- src/main/java/dev/aco/back/Entity/etc/Location.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/Repository/HashtagRepository.java
- src/main/java/dev/aco/back/Repository/LocationRepository.java
- src/main/java/dev/aco/back/Utils/Image/ImageManager.java
- src/main/java/dev/aco/back/VO/ChangeUserImgVO.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
페이징.. fetch로 해둔 놈들 수정했어영
검색결과는 테스트해보고 수정할게영
> [Hyunseok] Fix paging issue

- src/main/java/dev/aco/back/Repository/ArticleRepository.java
> [Hyunseok] Fix searching issue

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
> [Hyunseok] Fix paging issue final

- src/main/java/dev/aco/back/Admin/Service/AdminServiceImp.java
- src/main/java/dev/aco/back/DTO/Article/ArticleDTO.java
- src/main/java/dev/aco/back/DTO/Report/ArticleReportDTO.java
- src/main/java/dev/aco/back/DTO/Report/MemberReportDTO.java
- src/main/java/dev/aco/back/DTO/User/MemberDTO.java
> [Hyunseok] Add totalcount for each admin page

- src/main/java/dev/aco/back/Controller/ReportController.java
- src/main/java/dev/aco/back/Repository/MemberReportRepository.java
- src/main/java/dev/aco/back/service/ReportService/ReportService.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
Boolean > 게시글처럼 -1, 1, 2값으로 수정했어영
1 >  성공적으로 신고됨
-1 > 이미 신고함
2 > 신고에 실패함( 서버오류 )
> [Hyunseok] Fix member report as like article report

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
- src/main/java/dev/aco/back/service/ReportService/ReposrtServiceImpl.java
> [Hyunseok]Fix report member logic

- src/main/java/dev/aco/back/Controller/MemberSettingController.java
형준씨가 이미 만들어놓으셔서 컨트롤러만 살짝 수정해서 올립니다
vo는 글쓰기하듯 formdata에 추가해서 보내주시면 됩니당
> [Hyunseok] Fix controller for userimage upload

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Controller/LikeController.java
- src/main/java/dev/aco/back/Repository/ReplyRepository.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyService.java
- src/main/java/dev/aco/back/service/ArticleService/Reply/ReplyServiceImpl.java
{
"replyId": 1,
"member": {"memberId": 1},
"article": {"articleId": 1} 
}
JSON으로 이형태가 되게끔 api/article/reply/delete 보내주시면 됩니당
like의 api/api도 해결해놨어용
> [Hyunseok] Implement remove reply function and fix link issue

- src/main/java/dev/aco/back/Controller/ImageController.java
- src/main/java/dev/aco/back/Security/Filter/CustomUserFilter.java
- src/main/java/dev/aco/back/Security/Handler/CustomSuccessHandler.java
- src/main/java/dev/aco/back/Utils/JWT/JWTManager.java
- src/main/java/dev/aco/back/service/MemberService/MemberService.java
- src/main/java/dev/aco/back/service/MemberService/MemberServiceImpl.java
캐러셀 이미지 가져오듯 링크로 가져올수있는 기능 만들어놨구용
./api/image/user/멤버id
나머지 하나는 쿠키에도 userimg이름으로 이미지이름 넣어놨어용
> [Hyunseok] Implement request userimage function

- src/main/java/dev/aco/back/Repository/ArticleImageRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
이미지 모아서 한방에 수정하게끔 변경
basic.png 계속 저장되던 버그 수정
> [Hyunseok] Fix modify function

- src/main/java/dev/aco/back/Controller/ArticleController.java
- src/main/java/dev/aco/back/Repository/ArticleRepository.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleServiceImpl.java
get신호로 api/article/random으로 신호만 쏴주시면 string값 하나 나옵니다
대상은 아티클에서 메뉴가 tip일 경우 하나 뽑아서 가져옵니다
tip으로 쓰여진 글이 없으면 임시로 넣어둔 3개에서 하나 나옵니다
> [Hyunseok] Implement randomtip function temporary

- src/main/java/dev/aco/back/Controller/LikeController.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleLikeService.java
- src/main/java/dev/aco/back/service/ArticleService/ArticleLikeServiceImpl.java
요청에  성공하면 request한 article id 를 반환 
실패하면 -1반환
> [Hyunseok] Fix like function as requested

- aco-builder.sh
> [Hyunseok] Create shell-script for product automation
